name: ${project.name}
version: ${project.version}
main: org.mineacademy.foraryPlugin
author: Scuffi
description: Cursed library. Credit to TheAPI(EntityCreator), metalshark(GlowAPI), juliarn(NPC API)
api-version: 1.16
#depend: [ SmartInvs ]